### PR TITLE
Assign role

### PR DESCRIPTION
**Pull request by koooge**
Hi there, I propose an assign role option. How do you think about this?

### CODE REVIEW

**Comment by shibayu36** [comment]
Thanks for your pull request!

I think adding `-role` option to `opts` environment is better than adding role option.  Because using `opts` to pass options to mackerel-agent is simple and flexible.  For example, if we want to pass multiple roles, we just write `-e 'opts=-v -role=service1:docker1 -role=service2:docker2'`.

So I will just add `Assign a role` section to README.md( https://github.com/stanaka/docker-mackerel-agent/pull/19 ), and close this pull request.  But thanks again for your pull request!

**Comment by shibayu36** [comment]
I merged by mistake.  So I reverted it by https://github.com/stanaka/docker-mackerel-agent/commit/1e8bf7801b40af59a4a711ba695f4deacbc6631c

**Comment by itchyny** [comment]
Sorry I misunderstood the comments. The merge commit was reverted in 1e8bf7801b40af59a4a711ba695f4deacbc6631c in favor of #19.

**Comment by ghost** [comment]
:+1:

**Pull request merged**
